### PR TITLE
Refactor of the mapping.

### PR DESCRIPTION
**Pull request by bast**
Significant changes:
- a bit less code
- implemented a cache for the lookup function

### CODE REVIEW

**Comment by bast** [comment]
OK - I will remove the f-string in this patch.

**Comment by mathiasbockwoldt** [comment]
In `map.py` lines 26-33, it would remove an indentation level to use something like:
```python
            try:
                with open(file_name) as f:
                    f_reader = csv.reader(f, delimiter='\t', quotechar='"')
                    for k, v in f_reader:
                        l.append((k, v))
            except FileNotFoundError:
                sys.stderr.write(f'ERROR: file {file_name} not found\n')
            except TypeError: # this will catch file_name is None
                pass
```
(without the `if file_name is not None`).

Also, I think that using `sys.stderr.write` is maybe not as elegant as `print(..., file=sys.stderr)` or even using the logging module.

Both changes are of course kind of personal taste, though.

**Comment by bast** [comment]
I agree about `sys.stderr.write`.

I don't like except ... pass constructs (unless there is a very good motivation for them) and I think the `if file_name is not None` is more explicit.

**Comment by bast** [comment]
... and the reason why I don't like them is that I think they allow errors that we haven't imagined at this point to fall through the cracks.

**Comment by bast** [comment]
I changed to print. I agree that logging would be even better but I postponed that for later :-)

**Comment by mathiasbockwoldt** [comment]
Thank you! Yes, logging can be postponed so far :) The `except: pass` objection is good :)
Nice caching!

**Pull request merged**
